from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HelpEntry:
    command: str
    description: str
    example: str


HELP_ENTRIES = [
    HelpEntry(
        command="agentmesh --help",
        description="Show the built-in CLI help generated by Typer.",
        example="agentmesh --help",
    ),
    HelpEntry(
        command="agentmesh list-projects",
        description="List available spec-pack projects.",
        example="agentmesh list-projects",
    ),
    HelpEntry(
        command="agentmesh list-agents",
        description="List YAML-defined agents for a project.",
        example="agentmesh list-agents --project data_ops",
    ),
    HelpEntry(
        command="agentmesh validate-spec",
        description="Load and validate a project's YAML specs.",
        example="agentmesh validate-spec --project data_ops",
    ),
    HelpEntry(
        command="agentmesh init-project",
        description="Draft a new agent mesh from a user description, confirm it, then generate specs and starter Python code.",
        example='agentmesh init-project "Build a customer support triage mesh"',
    ),
    HelpEntry(
        command="agentmesh run",
        description=(
            "Run the mesh: resolve needs, select or synthesize agents, execute the "
            "dependency graph, and report tokens, cost, and retries per agent."
        ),
        example='agentmesh run --project data_ops "Review this SQL query" --max-cost 0.50',
    ),
    HelpEntry(
        command="agentmesh configure-models",
        description="Prompt for model provider access, API keys, and local model preferences, then write `.env`.",
        example="agentmesh configure-models",
    ),
    HelpEntry(
        command="agentmesh check-models",
        description="Verify provider credentials resolve; --live sends one tiny real request each.",
        example="agentmesh check-models --project data_ops --live",
    ),
    HelpEntry(
        command="agentmesh list-models",
        description="Show models configured for a project, provider availability, and estimated token costs.",
        example="agentmesh list-models --project data_ops",
    ),
    HelpEntry(
        command="uvicorn agentmesh.api.server:app --reload",
        description="Start the FastAPI wrapper around the same internal AgentMesh runtime.",
        example="uvicorn agentmesh.api.server:app --reload",
    ),
]


def list_help_entries() -> list[HelpEntry]:
    return HELP_ENTRIES
